# Generated by Django 4.2.7 on 2024-04-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ganoconcocacola',
            options={'verbose_name': 'Gano con Coca Cola Lead', 'verbose_name_plural': 'Gano con Coca Cola Leads'},
        ),
    ]
