# Generated by Django 4.2.7 on 2024-04-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_forms', '0002_alter_ganoconcocacola_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganoconcocacola',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
